### ISSUE TITLE
end of train.py

### ISSUE THREAD

**Issue by mymailpath** [ldulcic/chatbot#3]
having an issue  in following command:
find _frame occures for 4 times sequencly,
//
find_frame: frame not found.
    Looking for thread_id:pid_13674_id_140376588677072, frame_id:140374295187608
    Current     thread_id:pid_13674_id_140376588677072, available frames:
    256390088  -  257303304  -  257097320  -  261794232  -  256378632
140375085105680  -  40676968  -  140374563785000  -  140374362296488  -  140376107139736
140374563690808  -  140374563746744  -  140374563684152  -  140374362331944  -  140376375572648
258571928  -  40693192  -  40741384  -  40116344  -  40655992
39768040  -  34880856  -  

    Traceback (most recent call last):
  File "/snap/pycharm-community/128/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 213, in resolve
    return dict[key]
KeyError: 'kwargs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/pycharm-community/128/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1508, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
  File "/snap/pycharm-community/128/helpers/pydev/_pydevd_bundle/pydevd_vars.py", line 232, in getVariable
    var = resolver.resolve(var, k)
  File "/snap/pycharm-community/128/helpers/pydev/_pydevd_bundle/pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
AttributeError: 'dict' object has no attribute 'kwargs'

**Comment by ldulcic** [comment]
Hi @mymailpath, I don't see anything related to chatbot code in stacktrace, could you provide more info?

**Comment by mymailpath** [comment]
while executing the train.py , i got  an issue as above mentioned question(''find_frame: frame not found''.).
am i supposed to do provide any thread _is and  frame_id details directly in the program file ''pydevd_resolver.py''

and then further steps
error in the  file of 
{   
 ''File "/snap/pycharm-community/128/helpers/pydev/_pydevd_bundle/pydevd_comm.py", line 1508, in do_it
var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)   
 }



any ideas you have!

**Comment by ldulcic** [comment]
@mymailpath Seems like you executed `train.py` with debugger and ran out of memory.

**Comment by mymailpath** [comment]
yeah of course i did it and also got the output. But what the big issue  if we failed to give the parameter value for "save-every-epoch-at" then it skipped some and saves some randomly. We have to give epoch value in predict.py file and path for model files (args.model_path) @ldulcic . The major issue is training period : but the outputs are appreciated.

**Comment by ldulcic** [comment]
@mymailpath it's not saving models randomly, it saves every model which improves validation accuracy. I'm not sure I understand what is the question here, can you be more specific?

**Comment by mymailpath** [comment]
yeah buddy.  i did trained the data set to 50 epoch. But up to 10th epoch it works good, then failed(skips) to save the some of trained models afterwards.

Solution i provided the integer value for "saving-every-epoch" in hyper parameter section.

**Comment by ldulcic** [comment]
@mymailpath did you get good results?

**Comment by mymailpath** [comment]
stochastic outputs only. :-( 
But what i think is; if we suppose  train on more epoch level then, might be chance get the same output whereas represented  in dataset _(.csv)_files correspondingly.

**Comment by ldulcic** [comment]
@mymailpath try maybe with more complex model (increase hidden sizes of encoder and decoder)
