### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by mymailpath** [ldulcic/chatbot#4]
Hi. i do want to know , is there any values has to be given in this area 
 ->  [--train-embeddings] 
or in here
parser.add_argument('--train-embeddings', action='store_true',
                        help='Should gradients be propagated to word embeddings.')

**Comment by ldulcic** [comment]
@mymailpath no, this is boolean flag which indicates whether embeddings layer will be trainable.

**Comment by mymailpath** [comment]
Okay thanks and congratulations for your work

**Comment by ldulcic** [comment]
@mymailpath tnx :)
